import "server-only";
import { query, queryOne } from "./client";
import { embedOne, toVectorLiteral } from "../ai/embeddings";

export function normalizeAlias(input: string) { return input.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\s+/g," ").trim(); }
export interface ResolvedTarget { subjectId:string;subjectCode:string;name:string;route:string|null;matchedBy:"alias"|"exact_name"|"semantic";confidence:number }
export function resolveByAlias(userId:string,text:string) {
  return queryOne<ResolvedTarget>(`SELECT s.id "subjectId",s.subject_code "subjectCode",s.name,nt.route,'alias'::text "matchedBy",1.0::float8 confidence FROM agent.user_aliases ua JOIN academic.subjects s ON s.id=ua.target_id LEFT JOIN agent.navigation_targets nt ON nt.target_id=s.id AND nt.target_type='subject' WHERE ua.user_id=$1 AND ua.target_type='subject' AND lower(ua.alias)=$2`,[userId,normalizeAlias(text)]);
}
export function resolveByName(userId:string,text:string) {
  return query<ResolvedTarget>(`SELECT s.id "subjectId",s.subject_code "subjectCode",s.name,nt.route,'exact_name'::text "matchedBy",0.95::float8 confidence FROM academic.subjects s JOIN academic.enrollments e ON e.subject_id=s.id AND e.user_id=$1 LEFT JOIN agent.navigation_targets nt ON nt.target_id=s.id AND nt.target_type='subject' WHERE e.status='active' AND translate(lower(s.name),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc') LIKE '%'||$2||'%' ORDER BY length(s.name)`,[userId,normalizeAlias(text)]);
}
export type Resolution={kind:"found";target:ResolvedTarget}|{kind:"ambiguous";candidates:ResolvedTarget[]}|{kind:"not_found"};
const SIMILARITY_FLOOR=0.5;
export async function searchMemory(userId:string,queryText:string,limit=5){const safeLimit=Math.max(1,Math.min(limit,20));const vector=toVectorLiteral(await embedOne(queryText));const rows=await query<{id:string;content:string;memory_type:string;importance:number;similarity:number}>(`SELECT id,content,memory_type,importance,(1-(embedding <=> $2::vector))::float8 similarity FROM agent.memories WHERE user_id=$1 AND embedding IS NOT NULL AND (expires_at IS NULL OR expires_at>now()) ORDER BY embedding <=> $2::vector LIMIT $3`,[userId,vector,safeLimit]);const relevant=rows.filter(row=>row.similarity>=SIMILARITY_FLOOR);if(relevant.length)await query(`UPDATE agent.memories SET last_used_at=now() WHERE id=ANY($1::uuid[])`,[relevant.map(row=>row.id)]);return relevant;}
async function resolveBySemanticMemory(userId:string,text:string){const memories=await searchMemory(userId,text,5);for(const memory of memories){const targets=await query<ResolvedTarget>(`SELECT s.id "subjectId",s.subject_code "subjectCode",s.name,nt.route,'semantic'::text "matchedBy",$3::float8 confidence FROM academic.subjects s JOIN academic.enrollments e ON e.subject_id=s.id AND e.user_id=$1 LEFT JOIN agent.navigation_targets nt ON nt.target_id=s.id AND nt.target_type='subject' WHERE e.status='active' AND position(lower(s.name) in lower($2))>0`,[userId,memory.content,memory.similarity]);if(targets.length)return targets[0];}return null;}
export async function resolveSubject(userId:string,text:string):Promise<Resolution>{const alias=await resolveByAlias(userId,text);if(alias)return{kind:"found",target:alias};const candidates=await resolveByName(userId,text);if(candidates.length===1)return{kind:"found",target:candidates[0]};if(candidates.length>1)return{kind:"ambiguous",candidates};const semantic=await resolveBySemanticMemory(userId,text);return semantic?{kind:"found",target:semantic}:{kind:"not_found"};}
export function listNavigationTargets(institutionId:string|null){return query(`SELECT id,target_type,target_id,label,route FROM agent.navigation_targets WHERE institution_id=$1 OR institution_id IS NULL ORDER BY label`,[institutionId]);}
export function rememberAlias(userId:string,alias:string,targetType:string,targetId:string){return queryOne<{id:string}>(`INSERT INTO agent.user_aliases(user_id,alias,target_type,target_id) VALUES($1,$2,$3,$4) ON CONFLICT(user_id,lower(alias)) DO UPDATE SET target_id=EXCLUDED.target_id,target_type=EXCLUDED.target_type RETURNING id`,[userId,normalizeAlias(alias),targetType,targetId]);}
